### ISSUE TITLE
resnet missing issue

### ISSUE THREAD

**Issue by netrunner-exe** [clferrari/FacePartsSwap#3]
Hello! Thanks for this wonderful project! I tried to test it in Google Colab but unfortunately ran into an errors (besides missing _3DMM.py):
```
Traceback (most recent call last):
  File "main_c.py", line 3, in <module>
    from face_swap import face_swap
  File "/content/FacePartsSwap/face_swap.py", line 11, in <module>
    from evaluate import evaluate
  File "/content/FacePartsSwap/evaluate.py", line 13, in <module>
    from model import BiSeNet
  File "/content/FacePartsSwap/model.py", line 9, in <module>
    from resnet import Resnet18
ModuleNotFoundError: No module named 'resnet'
```

I take resnet.py from https://github.com/zllrunning/face-parsing.PyTorch but get another error:
```
Traceback (most recent call last):
  File "main_c.py", line 3, in <module>
    from face_swap import face_swap
  File "/content/FacePartsSwap/face_swap.py", line 12, in <module>
    from util_for_graphic import graphic_tools
  File "/content/FacePartsSwap/util_for_graphic.py", line 11, in <module>
    from matplotlib.mlab import griddata
ImportError: cannot import name 'griddata' from 'matplotlib.mlab' (/usr/local/lib/python3.7/dist-packages/matplotlib/mlab.py)
```

I fixed this issue by installing `!pip install --ignore-installed matplotlib==3.0`

Also i get during inference:
```
Bad key "text.kerning_factor" on line 4 in
/usr/local/lib/python3.7/dist-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
```
but it not affect inference

Then i tried to test on images from images_test folder but it not worked, I remove all `action='store_true'` from `main_c.py` and it helps.
After all it worked!

But unfortunately it does not work on my own images.

After testing on provided images i get this result:

`!python main_c.py --part 'face' --src_path "/content/FacePartsSwap/images_test/185.jpg" --dst_path "/content/FacePartsSwap/images_test/194.jpg"`
![swapped(1)](https://user-images.githubusercontent.com/81887288/189525663-71102a66-75fc-4c8b-816c-13a40e7f37d9.jpg)

Thank you!

**Comment by clferrari** [comment]
Hi, thank you for your help and for reporting these issues. I have pushed both the 3dmm and resnet files, now everything should be ok.

As for the bad results, I have run my code and get the same output as yours. After checking, I see landmarks are kind of badly detected on the woman's face... unfortunately, the method relies on landmarks and so if they are badly detected, it can fail. Also, large pose differences are difficult to handle.

To check if everything is correct, please run the code using the image 194.jpg as source and 196.jpg as target. If you swap the entire face, you should obtain the same image as in the main page (and the paper). I did this check now and it works properly. If you get the same image, then the code is correct.

![swapped](https://user-images.githubusercontent.com/39526399/189608189-2ebcfbdd-c049-4dea-b6ad-f09a93178cee.jpg)

Thank you again for your feedback and helping us improve the code!!
