### ISSUE TITLE
Bad gradient at "eyebrows" mode

### ISSUE THREAD

**Issue by DNotS** [clferrari/FacePartsSwap#4]
@clferrari, hello and thank you for your repository

When I am using `--part eyebrows` I often get image "broken". 
It specifically often happens with images with male persons.
I even ran this command with same image, like this:
`python3 main_c.py --src_path act_99_square.png --dst_path act_99_square.png --part eyebrows --debug`
My guess is that something is wrong with gradient.
What should I do to fix this problem?

Many thanks in advance.
I am using Ubuntu 20.04.5 LTS, python 3.8. Attaching mentioned image, resulted image and file with packages' version ([packages.txt](https://github.com/clferrari/FacePartsSwap/files/10001019/packages.txt)).
![act_99_square](https://user-images.githubusercontent.com/15313147/201611365-67063159-2432-47a8-b26d-ec4bbcbf13c5.png)
![swapped](https://user-images.githubusercontent.com/15313147/201611285-f5bb35e7-728a-41ac-a21c-4f950d185482.jpg)

**Comment by DNotS** [comment]
Hello and thank you for fast fix, @clferrari! I've tried with the image that I have provided previously and it worked fine for it.

However, I ran some additional experiments with different images. I also have results for them from previous version.To a lesser extent, but the problem remains.
[FacePartsSwap_experiments.zip](https://github.com/clferrari/FacePartsSwap/files/10029127/FacePartsSwap_experiments.zip)

Donor_* - from whom I have taken facial feature
Recipient_* - who got his/her facial feature swapped
swapped_eyebrows_*_new - swapped eyebrows after fix
swapped_eyebrows_*_old - swapped eyebrows before fix

Many thanks for your work!

**Comment by DNotS** [comment]
Hello and thank you for fast fix, @clferrari! I've tried with the image that I have provided previously and it worked fine for it.

However, I ran some additional experiments with different images. I also have results for them from previous version.To a lesser extent, but the problem remains.
[FacePartsSwap_experiments.zip](https://github.com/clferrari/FacePartsSwap/files/10029127/FacePartsSwap_experiments.zip)

Donor_* - from whom I have taken facial feature
Recipient_* - who got his/her facial feature swapped
swapped_eyebrows_new - swapped eyebrows after fix
swapped_eyebrows_old - swapped eyebrows before fix

Many thanks for your work!

**Comment by clferrari** [comment]
Hi @DNotS 

I checked your examples and indeed the fix seem to partially solve the issue. I ran your examples, and think there are two possible causes: (1) errors in landmark detection or (2) the seamless clone cannot correctly merge very different textures if the swapped area is large.

While the first issue is not really solvable (unless trying a more accurate detector, unfortunately our method depends on that), one workaround to mitigate the second one is the following: when you want to swap either eyes or eyebrows, try to do that separately. What I mean is:

- swap the left/right eyebrow/eye and save the intermediate image I_s
- swap the other eyebrow/eye using I_s in place of the original one

This workaround would solve the triangulation issue I mentioned in the previous message, which I'm trying to solve. In particular, when performing the triangulation, if both eyebrows or eyes are swapped, the triangulation that is estimated would join also point from the two eyes/eyebrows, so including patches in-between them, from the upper part of the nose/forehead. 

I know this is not the optimal solution but it helps to avoid that problem. I will try to re-write the swap function to account for that more efficiently.

If you try that I would be glad if you could share the results. Thanks for helping us identifying the limitations and improving our work!
Claudio

**Comment by DNotS** [comment]
Hi @clferrari 

I have tried your suggested approach and it worked fine. Sadly it blurred final image twice and also added black border twice. Will it help if I will use swapped_raw after first step? Or if I rise resolution of output image?

Since I am interested in swapping facial features of people looking straight into the camera, I am also thinking about creating separate images (one after swapping only left eyebrow and one after swapping only right eyebrow) and then taking left and right part of the image accordingly. Just as a workaround for now.

Adding archive with experiments: [FacePartsSwap_experiments.zip](https://github.com/clferrari/FacePartsSwap/files/10030723/FacePartsSwap_experiments.zip)

I also fixed small typo in the paths of files to the eyebrow indexes.

**Comment by clferrari** [comment]
Hi @DNotS 

yes, the best thing is to use swapped_raw as intermediate image for this step. I have used the blurring process for correcting minor artifacts for the purpose of conducting face recognition experiments as described in the paper. Face recognition networks are indeed robust to blur. Qualitatively this will make the image less detailed of course, so try using the raw one.

I will try to solve this issue by triangulating the two regions separately. Hopefully this would improve and simplify the overall process.

Thank you for noticing the typo, I noticed that too. Will push everything as soon as possible.

Thanks
Claudio

**Comment by DNotS** [comment]
Thank you!
I will wait for the changes!

**Comment by DNotS** [comment]
Hello @clferrari 

It seems like everything works just fine now and I did not find any new issues.
Thank you for you work!

**Comment by DNotS** [comment]
Hello @clferrari 

I found that now sometimes (pretty often) there are no swapping of second eyebrow (left or right) and sometimes there are no eye swapping. Please, check these results and original images: [tests.zip](https://github.com/clferrari/FacePartsSwap/files/10081487/tests.zip)

**Comment by clferrari** [comment]
Hi @DNotS 

I should have fixed this further bug. Please pull again and check if now everything works properly. 

Thanks
Claudio
